services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_list
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    depends_on:
      - mysql
    environment:
      DB_TYPE: "mysql"
      DB_HOST: "mysql"
      DB_PORT: 3336
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      DB_NAME: "todo_list"


  frontend:
    restart: always
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        DOCKER_BUILDKIT: 1

volumes:
  mysql_data:
